### ISSUE TITLE
Error enabling add-on

### ISSUE THREAD

**Issue by javgoji** [mrachinskiy/jewelcraft#16]
![Captura de pantalla 2019-05-13 a las 8 00 01](https://user-images.githubusercontent.com/14369837/57599145-0dc28580-7556-11e9-8933-d6cf9b577d16.png)
![Captura de pantalla 2019-05-13 a las 8 00 45](https://user-images.githubusercontent.com/14369837/57599175-2468dc80-7556-11e9-823d-7ace03dd91da.png)
![Captura de pantalla 2019-05-13 a las 8 08 17](https://user-images.githubusercontent.com/14369837/57599237-537f4e00-7556-11e9-9686-c6f311e55813.png)

**Comment by mrachinskiy** [comment]
You downloaded repository instead of release. Please use [How to install](https://github.com/mrachinskiy/jewelcraft#how-to-install) guide.

**Comment by javgoji** [comment]
same error 2.3.1 pre release Blender 2.80

**Comment by mrachinskiy** [comment]
Are you sure it's the same error?

1. Open Blender (if it's already opened close and reopen).
2. Enable JewelCraft.
3. If error occurs take the screenshot and post it here.

It is important that you would not try to invoke the error second time on the same instance of Blender, because it will change the error message to something unrelated (that's why step one is important).

**Comment by javgoji** [comment]
You are ok.I had to close and reopen Blender to avoid error.Blender was keeping the subclass instance before.Thank you
    En lunes, 13 de mayo de 2019 14:02:45 CEST, Mikhail Rachinskiy <notifications@github.com> escribió:  
 
 
Are you sure it's the same error?
   
   - Open Blender (if it's already opened close and reopen).
   - Enable JewelCraft.
   - If error occurs take the screenshot and post it here.

It is important that you would not try to invoke the error second time on the same instance of Blender, because it will change the error message to something unrelated (that's why step one is important).
