### ISSUE TITLE
New Spanish Language for Jewelcraft

### ISSUE THREAD

**Issue by Oxervision** [mrachinskiy/jewelcraft#50]
Hi, I translated all strings to Spanish and I added some missing translations. The zip file includes the .po & .mo files.
Thanks for this fantastic addon!!

Regards,

Oxer

[Spanish Language.zip](https://github.com/mrachinskiy/jewelcraft/files/8976898/Spanish.Language.zip)

**Comment by mrachinskiy** [comment]
Thank you so much!

Since last JewelCraft release four new lines have been added for translation, would you mind translating those?

- Limit by Selection
- Keep Z Direction
- Makes transforms on Z axis consistent with original object (does not affect gems)
- Curve start position

You do not need to provide `.mo` file, Blender add-on API does not support it anyway. I converted all translations to `.po` format by request from a translator to simplify contribution process.

Do you have any social media page I could feature in announcement? If not not then I can feature your GitHub profile instead.

Can you also provide me your name so I could specify it in announcement and translation file?

**Comment by Oxervision** [comment]
Hi, I have included the new lines to the Spanish translation.

My social media pages:

https://www.facebook.com/Oxervision

https://www.artstation.com/oxer

Regards,

Óscar (Oxer)

[Spanish Translation.zip](https://github.com/mrachinskiy/jewelcraft/files/9028899/Spanish.Translation.zip)

**Comment by mrachinskiy** [comment]
Hi, thank you for updated translation, I noticed that you left certain entries untranslated:

- Baguette
- Asscher
- Radiant
- Flanders

Is that because the Spanish spelling for these words is exactly the same as English? Or it is adopted terminology?

**Comment by Max-Villafranca** [comment]
Baguette
Asscher
Radiant
Flanders

they are adopted, but in cases where we have a direct translation most spanish speaking countries use the native word
that is the case of Radiant, we use <Radiante>

**Comment by mrachinskiy** [comment]
@Max-Villafranca thank you for clarification, updated translation will be available in the next release.
